apiVersion: v1
kind: Service
metadata:
  name: {{ include "fivenet.fullname" . }}
  labels:
    app.kubernetes.io/component: server
    {{- include "fivenet.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: http
    - name: metrics
      port: 7070
      protocol: TCP
      targetPort: metrics
    - name: grpc
      port: 9090
      protocol: TCP
      targetPort: grpc
  selector:
    app.kubernetes.io/component: server
    {{- include "fivenet.selectorLabels" . | nindent 4 }}
